version: '2'

services:
  kafka1:
    image: blueskyareahm/kafka:2.6.0
    hostname: doc-kafka1.local
    container_name: kafka1
    ports:
      - 2181:2181
      - 9092:9092
    mem_limit: 512m
    networks:
      spark-nw:
        ipv4_address: 172.30.1.20

networks:
  spark-nw:
    external: true
