version: '2'

services:
  master:
    build:
      context: .
      dockerfile: ./Dockerfile.cluster
    image: my/hdp-cluster
    hostname: spark-master
    container_name: my-spark-master
    ports:
      - "8040:8040"
      - "8088:8088"
      - "9000:9000"
      - "19888:19888"
      - "50070:50070"
    mem_limit: 1g
    environment:
      TAG: MASTER

