version: '2'

services:
  spark-master:
    image: blueskyareahm/spark-livy-base:0.7.0
    hostname: doc-spark-master-livy101.local
    container_name: spark-master-livy101
    ports:
      - 4040:4040
      - 8080:8080
      - 7077:7077
      - 8998:8998
    mem_limit: 1g
    networks:
      spark-nw:
        ipv4_address: 172.30.1.2
    command: /spark/bin/spark-class org.apache.spark.deploy.master.Master --host 0.0.0.0 --port 7077 --webui-port 8080
    extra_hosts:
      - "doc-spark-worker-livy101.local:172.30.1.3"

  spark-worker:
    image: blueskyareahm/spark-livy-base:0.7.0
    hostname: doc-spark-worker-livy101.local
    container_name: spark-worker-livy101
    depends_on:
      - spark-master
    ports:
      - 4041:4040
      - 8081:8080
      - 8999:8998
    mem_limit: 1g
    networks:
      spark-nw:
        ipv4_address: 172.30.1.3
    command: /spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://172.30.1.2:7077 --host 172.30.1.3
    extra_hosts:
      - "doc-spark-master-livy101.local:172.30.1.2"
 
networks:
  spark-nw:
    external: true
